package cherokee.dictionary.hold.wordFormation

class TransitiveVerb extends BaseVerb  {
    def SG1SG1   
    def SG1SG2 
    def SG1SG3AN 
    def SG1SG3IN 
    def SG1DL1INCL 
    def SG1DL1EXCL 
    def SG1PL1INCL 
    def SG1PL1EXCL 
    def SG1DL2 
    def SG1PL2 
    def SG1PL3AN 
    def SG1PL3IN 
    def SG2SG1 
    def SG2SG2 
    def SG2SG3AN 
    def SG2SG3IN 
    def SG2DL1INCL 
    def SG2DL1EXCL 
    def SG2PL1INCL 
    def SG2PL1EXCL 
    def SG2DL2 
    def SG2PL2 
    def SG2PL3AN 
    def SG2PL3IN 
    def SG3SG1 
    def SG3SG2 
    def SG3SG3AN 
    def SG3SG3IN 
    def SG3DL1INCL 
    def SG3DL1EXCL 
    def SG3PL1INCL 
    def SG3PL1EXCL 
    def SG3DL2 
    def SG3PL2 
    def SG3PL3AN 
    def SG3PL3IN 
    def DL1INCLSG1 
    def DL1INCLSG2 
    def DL1INCLSG3AN 
    def DL1INCLSG3IN 
    def DL1INCLDL1INCL 
    def DL1INCLDL1EXCL 
    def DL1INCLPL1INCL 
    def DL1INCLPL1EXCL 
    def DL1INCLDL2 
    def DL1INCLPL2 
    def DL1INCLPL3AN 
    def DL1INCLPL3IN 
    def DL1EXCLSG1 
    def DL1EXCLSG2 
    def DL1EXCLSG3AN 
    def DL1EXCLSG3IN 
    def DL1EXCLDL1INCL 
    def DL1EXCLDL1EXCL 
    def DL1EXCLPL1INCL 
    def DL1EXCLPL1EXCL 
    def DL1EXCLDL2 
    def DL1EXCLPL2 
    def DL1EXCLPL3AN 
    def DL1EXCLPL3IN 
    def PL1INCLSG1 
    def PL1INCLSG2 
    def PL1INCLSG3AN 
    def PL1INCLSG3IN 
    def PL1INCLDL1INCL 
    def PL1INCLDL1EXCL 
    def PL1INCLPL1INCL 
    def PL1INCLPL1EXCL 
    def PL1INCLDL2 
    def PL1INCLPL2 
    def PL1INCLPL3AN 
    def PL1INCLPL3IN 
    def PL1EXCLSG1 
    def PL1EXCLSG2 
    def PL1EXCLSG3AN 
    def PL1EXCLSG3IN 
    def PL1EXCLDL1INCL 
    def PL1EXCLDL1EXCL 
    def PL1EXCLPL1INCL 
    def PL1EXCLPL1EXCL 
    def PL1EXCLDL2 
    def PL1EXCLPL2 
    def PL1EXCLPL3AN 
    def PL1EXCLPL3IN 
    def DL2SG1 
    def DL2SG2 
    def DL2SG3AN 
    def DL2SG3IN 
    def DL2DL1INCL 
    def DL2DL1EXCL 
    def DL2PL1INCL 
    def DL2PL1EXCL 
    def DL2DL2 
    def DL2PL2 
    def DL2PL3AN 
    def DL2PL3IN 
    def PL2SG1 
    def PL2SG2 
    def PL2SG3AN 
    def PL2SG3IN 
    def PL2DL1INCL 
    def PL2DL1EXCL 
    def PL2PL1INCL 
    def PL2PL1EXCL 
    def PL2DL2 
    def PL2PL2 
    def PL2PL3AN 
    def PL2PL3IN 
    def PL3SG1 
    def PL3SG2 
    def PL3SG3AN 
    def PL3SG3IN 
    def PL3DL1INCL 
    def PL3DL1EXCL 
    def PL3PL1INCL 
    def PL3PL1EXCL 
    def PL3DL2 
    def PL3PL2 
    def PL3PL3AN 
    def PL3PL3IN 
}
