package cherokee.dictionary.conjugation

import SyllabaryUtil

class CEDGrammarVerbTest extends GroovyTestCase {
    def su = new SyllabaryUtil()

    public void testPage265(){
        rootProcessorForCompare("gvyvniha", "vni", "h")
        rootProcessorForCompare("jiyvniha", "vni", "h")
        rootProcessorForCompare("gvniha", "vni", "h")
        rootProcessorForCompare("sdvniha", "vni", "h")
        rootProcessorForCompare("ijvniha", "vni", "h")
        rootProcessorForCompare("gajiyvniha", "vni", "h")
        rootProcessorForCompare("degvniha", "vni", "h")
        rootProcessorForCompare("sgwvniha", "vni", "h")
        rootProcessorForCompare("hiyvniha", "vni", "h")
        rootProcessorForCompare("hvniha", "vni", "h")
        rootProcessorForCompare("sginvniha", "vni", "h")
        rootProcessorForCompare("isgiyvvniha", "vni", "h")
        rootProcessorForCompare("gahiyvniha", "vni", "h")
        rootProcessorForCompare("dehvniha", "vni", "h")
        rootProcessorForCompare("agwvniha", "vni", "h")
        rootProcessorForCompare("jvniha", "vni", "h")
        rootProcessorForCompare("gvniha", "vni", "h")
        rootProcessorForCompare("giniha", "vni", "h")
        rootProcessorForCompare("igvniha", "vni", "h")
        rootProcessorForCompare("oginiha", "vni", "h")
        rootProcessorForCompare("ogvniha", "vni", "h")
        rootProcessorForCompare("sdvniha", "vni", "h")
        rootProcessorForCompare("ijvniha", "vni", "h")
        rootProcessorForCompare("degvniha", "vni", "h")
        rootProcessorForCompare("envniha", "vni", "h")
        rootProcessorForCompare("invniha", "vni", "h")
        rootProcessorForCompare("genvniha", "vni", "h")
        rootProcessorForCompare("denvniha", "vni", "h")
        rootProcessorForCompare("denvniha", "vni", "h")
        rootProcessorForCompare("edvniha", "vni", "h")
        rootProcessorForCompare("idvniha", "vni", "h")
        rootProcessorForCompare("gedvniha", "vni", "h")
        rootProcessorForCompare("dedvniha", "vni", "h")
        rootProcessorForCompare("sdvyvniha", "vni", "h")
        rootProcessorForCompare("osdvniha", "vni", "h")
        rootProcessorForCompare("sdvyvniha", "vni", "h")
        rootProcessorForCompare("ijvyvniha", "vni", "h")
        rootProcessorForCompare("gosdvniha", "vni", "h")
        rootProcessorForCompare("dosdvniha", "vni", "h")
        rootProcessorForCompare("ijvyvniha", "vni", "h")
        rootProcessorForCompare("ojvniha", "vni", "h")
        rootProcessorForCompare("ojvniha", "vni", "h")
        rootProcessorForCompare("ijvyvniha", "vni", "h")
        rootProcessorForCompare("gojvniha", "vni", "h")
        rootProcessorForCompare("dojvniha", "vni", "h")
        rootProcessorForCompare("sginvniha", "vni", "h")
        rootProcessorForCompare("esdvniha", "vni", "h")
        rootProcessorForCompare("sdvniha", "vni", "h")
        rootProcessorForCompare("sginvniha", "vni", "h")
        rootProcessorForCompare("isginvniha", "vni", "h")
        rootProcessorForCompare("gesdvniha", "vni", "h")
        rootProcessorForCompare("desdvniha", "vni", "h")
        rootProcessorForCompare("isgiyvniha", "vni", "h")
        rootProcessorForCompare("ejvniha", "vni", "h")
        rootProcessorForCompare("ijvniha", "vni", "h")
        rootProcessorForCompare("isgiyvniha", "vni", "h")
        rootProcessorForCompare("gejvniha", "vni", "h")
        rootProcessorForCompare("dejvniha", "vni", "h")
        rootProcessorForCompare("gvgwvniha", "vni", "h")
        rootProcessorForCompare("gejvniha", "vni", "h")
        rootProcessorForCompare("anvniha", "vni", "h")
        rootProcessorForCompare("geginvniha", "vni", "h")
        rootProcessorForCompare("gegvniha", "vni", "h")
        rootProcessorForCompare("goginvniha", "vni", "h")
        rootProcessorForCompare("gogvniha", "vni", "h")
        rootProcessorForCompare("gesdvniha", "vni", "h")
        rootProcessorForCompare("gejvniha", "vni", "h")
        rootProcessorForCompare("danvniha", "vni", "h")
    }

    public void testPage267() {
        rootProcessorForCompare("gvgowatiha", "gowati", "h")
        rootProcessorForCompare("jigowatiha", "gowati", "h")
        rootProcessorForCompare("jigowatiha", "gowati", "h")
        rootProcessorForCompare("sdvgowatiha", "gowati", "h")
        rootProcessorForCompare("ijvgowatiha", "gowati", "h")
        rootProcessorForCompare("gajigowatiha", "gowati", "h")
        rootProcessorForCompare("dejigowatiha", "gowati", "h")
        rootProcessorForCompare("sgigowatiha", "gowati", "h")
        rootProcessorForCompare("higowatiha", "gowati", "h")
        rootProcessorForCompare("higowatiha", "gowati", "h")
        rootProcessorForCompare("sginigowatiha", "gowati", "h")
        rootProcessorForCompare("isgigowatiha", "gowati", "h")
        rootProcessorForCompare("gahigowatiha", "gowati", "h")
        rootProcessorForCompare("dehigowatiha", "gowati", "h")
        rootProcessorForCompare("agigowatiha", "gowati", "h")
        rootProcessorForCompare("jagowatiha", "gowati", "h")
        rootProcessorForCompare("agowatiha", "gowati", "h")
        rootProcessorForCompare("ginigowatiha", "gowati", "h")
        rootProcessorForCompare("igigowatiha", "gowati", "h")
        rootProcessorForCompare("ogigowatiha", "gowati", "h")
        rootProcessorForCompare("ogigowatiha", "gowati", "h")
        rootProcessorForCompare("sdigowatiha", "gowati", "h")
        rootProcessorForCompare("ijigowatiha", "gowati", "h")
        rootProcessorForCompare("dagowatiha", "gowati", "h")
        rootProcessorForCompare("enigowatiha", "gowati", "h")
        rootProcessorForCompare("inigowatiha", "gowati", "h")
        rootProcessorForCompare("genigowatiha", "gowati", "h")
        rootProcessorForCompare("denigowatiha", "gowati", "h")
        rootProcessorForCompare("edigowatiha", "gowati", "h")
        rootProcessorForCompare("idigowatiha", "gowati", "h")
        rootProcessorForCompare("gedigowatiha", "gowati", "h")
        rootProcessorForCompare("dedigowatiha", "gowati", "h")
        rootProcessorForCompare("sdvgowatiha", "gowati", "h")
        rootProcessorForCompare("osdigowatiha", "gowati", "h")
        rootProcessorForCompare("osdigowatiha", "gowati", "h")
        rootProcessorForCompare("sdvgowatiha", "gowati", "h")
        rootProcessorForCompare("ijvgowatiha", "gowati", "h")
        rootProcessorForCompare("gosdigowatiha", "gowati", "h")
        rootProcessorForCompare("dosdigowatiha", "gowati", "h")
        rootProcessorForCompare("ijvgowatiha", "gowati", "h")
        rootProcessorForCompare("ojigowatiha", "gowati", "h")
        rootProcessorForCompare("ojigowatiha", "gowati", "h")
        rootProcessorForCompare("ijvgowatiha", "gowati", "h")
        rootProcessorForCompare("gojigowatiha", "gowati", "h")
        rootProcessorForCompare("dojigowatiha", "gowati", "h")
        rootProcessorForCompare("sginigowatiha", "gowati", "h")
        rootProcessorForCompare("esdigowatiha", "gowati", "h")
        rootProcessorForCompare("sdigowatiha", "gowati", "h")
        rootProcessorForCompare("sginigowatiha", "gowati", "h")
        rootProcessorForCompare("isgigowatiha", "gowati", "h")
        rootProcessorForCompare("gesdigowatiha", "gowati", "h")
        rootProcessorForCompare("desdigowatiha", "gowati", "h")
        rootProcessorForCompare("isgigowatiha", "gowati", "h")
        rootProcessorForCompare("ejigowatiha", "gowati", "h")
        rootProcessorForCompare("ijigowatiha", "gowati", "h")
        rootProcessorForCompare("isgigowatiha", "gowati", "h")
        rootProcessorForCompare("gejigowatiha", "gowati", "h")
        rootProcessorForCompare("dejigowatiha", "gowati", "h")
        rootProcessorForCompare("gvgigowatiha", "gowati", "h")
        rootProcessorForCompare("gejagowatiha", "gowati", "h")
        rootProcessorForCompare("anigowatiha", "gowati", "h")
        rootProcessorForCompare("geginigowatiha", "gowati", "h")
        rootProcessorForCompare("geginigowatiha", "gowati", "h")
        rootProcessorForCompare("gegigowatiha", "gowati", "h")
        rootProcessorForCompare("goginigowatiha", "gowati", "h")
        rootProcessorForCompare("gogigowatiha", "gowati", "h")
        rootProcessorForCompare("gesdigowatiha", "gowati", "h")
        rootProcessorForCompare("gejigowatiha", "gowati", "h")
        rootProcessorForCompare("danigowatiha", "gowati", "h")
    }

    public void testForgetPage268() {
        rootProcessorForCompare("agwvkewisga", "kewis", "g")
        rootProcessorForCompare("dagwvkewisga", "kewis", "g")
        rootProcessorForCompare("jvkewisga", "kewis", "g")
        rootProcessorForCompare("dejvkewisga", "kewis", "g")
        rootProcessorForCompare("gvkewisga", "kewis", "g")
        rootProcessorForCompare("uwakewisga", "kewis", "g")
        rootProcessorForCompare("degvkewisga", "kewis", "g")
        rootProcessorForCompare("duwakewisga", "kewis", "g")
        rootProcessorForCompare("ginvkewisga", "kewis", "g")
        rootProcessorForCompare("deginvkewisga", "kewis", "g")
        rootProcessorForCompare("igvkewisga", "kewis", "g")
        rootProcessorForCompare("degvkewisga", "kewis", "g")
        rootProcessorForCompare("osdvkewisga", "kewis", "g")
        rootProcessorForCompare("oginvkewisga", "kewis", "g")
        rootProcessorForCompare("dosdvkewisga", "kewis", "g")
        rootProcessorForCompare("doginvkewisga", "kewis", "g")
        rootProcessorForCompare("ojvkewisga", "kewis", "g")
        rootProcessorForCompare("ogvkewisga", "kewis", "g")
        rootProcessorForCompare("ogvkewisga", "kewis", "g")
        rootProcessorForCompare("gojvkewisga", "kewis", "g")
        rootProcessorForCompare("dogvkewisga", "kewis", "g")
        rootProcessorForCompare("anvkewisga", "kewis", "g")
        rootProcessorForCompare("unvkewisga", "kewis", "g")
        rootProcessorForCompare("danvkewisga", "kewis", "g")
        rootProcessorForCompare("dunvkewisga", "kewis", "g")
    }

    public void testToLikePage270() {
        //todo: fix ᏋᎡᏫᏍg not a valid letterᎡᏫᏍg
        rootProcessorForCompare("agwvkewisga", "kewis", "g")
    }

    public void testSolo() {
        rootProcessorForCompare("agowatiha", "gowati", "h")
    }

    private void rootProcessorForCompare(original, assertion, ending) {
        original = su.tsalagiToSyllabary(original)
        assertion = su.tsalagiToSyllabary(assertion)+ending


        ConjugateBase.compareForAssertion(original,assertion)
        ConjugateBase.processRootForCompare(original, assertion)
    }
}
